/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm_java2;

import dao.NganhHocDao;
import dao.SinhVienDao;
import entity.NganhHoc;
import entity.SinhVien;
import java.util.ArrayList;
import java.util.List;
import uliti.Dialog;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuCute
 */
public class SinhVienJFrame extends javax.swing.JFrame {

    private SinhVienDao sinhVienDao;
    private NganhHocDao nganhHocDao;
    List<SinhVien> lstSinhVien = new ArrayList<>();
    List<NganhHoc> lstNganhHoc = new ArrayList<>();

    /**
     * Creates new form SinhVienJFrame
     */
    public SinhVienJFrame() throws Exception {
        initComponents();
        setTitle("QL SINH VIÊN");
        setLocationRelativeTo(null);
        sinhVienDao = new SinhVienDao();
        nganhHocDao = new NganhHocDao();
        lstNganhHoc = nganhHocDao.getAllData();
        filltable();
        fillcbbNganhHoc();
    }

    private void resfesh() {
        txt_tensv.setText("");
        txt_masv.setText("");;
        txt_diem.setText("");
        cbb_nganhhoc.setSelectedIndex(0);
    }

    private void addSinhVien() {
        SinhVien sinhVien = getForm();
        if (sinhVienDao.addSinhVien(sinhVien)) {
            Dialog.pass("Thêm");
            filltable();
        } else {
            Dialog.fail("Thêm");
            return;
        }
    }

    private void updateSinhVien() {
        SinhVien sinhVien = getForm();
        if (sinhVienDao.updateSinhVien(sinhVien)) {
            Dialog.pass("Sửa");
            filltable();
        } else {
            Dialog.fail("Sửa");
            return;
        }
    }

    private void deleteSinhVien() {
        SinhVien sinhVien = getForm();
        if (sinhVienDao.deletedSinhVien(sinhVien)) {
            Dialog.pass("Xoá");
            filltable();
        } else {
            Dialog.fail("Xoá");
            return;
        }
    }

    private SinhVien getForm() {
        String masv = txt_masv.getText();
        String tensv = txt_tensv.getText();
        double diem = Double.parseDouble(txt_diem.getText());
        String manh = getMaNH();
        SinhVien sinhVien = new SinhVien(masv, manh, tensv, diem);
        return sinhVien;
    }

    private void setForm(int index) {
        if (index < 0) {
            return;
        }
        SinhVien sinhVien = lstSinhVien.get(index);
        txt_tensv.setText(sinhVien.getTensv());
        txt_masv.setText(sinhVien.getMasv());
        txt_diem.setText(String.valueOf(sinhVien.getDiem()));
        cbb_nganhhoc.setSelectedItem(sinhVien.getManh());
    }

    private String getMaNH() {
        int index = cbb_nganhhoc.getSelectedIndex();
        if (index < 0) {
            return null;
        }
        NganhHoc nganhHoc = lstNganhHoc.get(index);
        return nganhHoc.getManh();
    }

    private void fillcbbNganhHoc() {
        cbb_nganhhoc.removeAllItems();
        for (NganhHoc nganhHoc : lstNganhHoc) {
            cbb_nganhhoc.addItem(nganhHoc.getTennh());
        }
    }

    private void filltable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_SinhVien.getModel();
        defaultTableModel.setRowCount(0);
        try {
            lstSinhVien = sinhVienDao.getAllData();
            if (lstSinhVien.isEmpty()) {
                System.out.println("Danh Sách Trống");
                return;
            }
            for (SinhVien sinhVien : lstSinhVien) {
                Object[] row = {
                    sinhVien.getMasv(),
                    sinhVien.getTensv(),
                    sinhVien.getManh(),
                    sinhVien.getDiem()
                };
                defaultTableModel.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("Mã Lỗi: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        txt_tensv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_diem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbb_nganhhoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SinhVien = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Sinh Viên");

        jLabel2.setText("Tên Sinh Viên");

        jLabel3.setText("Điểm");

        jLabel4.setText("Ngành Học");

        cbb_nganhhoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_SinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SV", "Tên SV", "Ngành Học", "Điểm"
            }
        ));
        tbl_SinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SinhVien);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_tensv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_diem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80))
                    .addComponent(cbb_nganhhoc, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                    .addComponent(txt_masv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(69, 69, 69)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_moi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Xoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_nganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_moi)
                    .addComponent(btn_sua)
                    .addComponent(btn_Xoa))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        addSinhVien();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        updateSinhVien();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        deleteSinhVien();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        // TODO add your handling code here:
        resfesh();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void tbl_SinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SinhVienMouseClicked
        // TODO add your handling code here:
        int row = tbl_SinhVien.getSelectedRow();
        setForm(row);
    }//GEN-LAST:event_tbl_SinhVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SinhVienJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SinhVienJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cbb_nganhhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SinhVien;
    private javax.swing.JTextField txt_diem;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_tensv;
    // End of variables declaration//GEN-END:variables
}
